### ISSUE TITLE
atmodat checker fails to detect wrong global attribute encoding

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#103]
I have a netcdf file whose global metadata should comply with the ATMODAT.
I created the file with xarray, and, unfortunately, xarray prepends the string "string :" to the global attributes title, history, institution, source, references, and comment. 

Note, these are the global attributes recommended in the CF conventions https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#description-of-file-contents.
 
Here is an example of the header:
```
ncdump -h  lwtns06_1986.nc|grep string
		string :creator = "Peter Loewe, Bundesamt für Seeschifffahrt und Hydrographie (BSH), ORCID: 0000-0001-8243-2111, url: https://www.bsh.de/EN/Home/home_node.html" ;
		string :institution = "Bundesamt für Seeschifffahrt und Hydrographie, Bernhard-Nocht-Straße 78, 20359 Hamburg, Germany" ;
		string :summary = "Sea level pressure is a fundamental weather and climate element and the very basis of everyday weather maps. Daily sea level [..]

```

The atmodat checker does not detect this issue. institution, for example, is a mandatory ATMODAT global attribute. 
But when I run the atmodat checker over the file, it does not provoke any error in the global attributes. 

```
run_checks -s -f lwtns06_1986.nc
Running Compliance Checker on the datasets from: ['lwtns06_1986.nc']
[...]
(adc2) angelika ~/CFdata/BSH: more atmodat_checker_output/latest/short_summary.txt
Short summary of checks:

Checking against: atmodat_standard:3.0, CF table version: 78
Version of the AtMoDat checker: 1.1.0
Checked at: 2022-01-11T14:06:07

Number of checked files: 1
*Mandatory checks passed: 5/5*
Recommended checks passed: 15/19
Optional checks passed: 6/9
CF checker errors: 0
```

So, the atmodat checker treats 
string :institution = "Bundesamt für Seeschifffahrt und Hydrographie, Bernhard-Nocht-Straße 78, 20359 Hamburg, Germany" ;
as if it was
institution = "Bundesamt für Seeschifffahrt und Hydrographie, Bernhard-Nocht-Straße 78, 20359 Hamburg, Germany" ;

Thanks a lot

**Comment by jkretz** [comment]
Well I don't think this is an issue of the checker. The `string :` just tells you the data type of the attribute, which in your case is a string. As the checker only checks for the presence and the content of the respective attribute, the `string :`  is not even used. As for all your examples the content of the attribute is valid and in compliance with the standard, all checks will pass. I don't think this is a problem of the checker and is also nothing that needs to be addressed.
I remember that I once ran into a similar issue with the netCDF4 python packages, but can recall how to get rid of the `string :`

**Comment by atmodatcode** [comment]
The CF conventions document shows no netcdf header example with 'string : attribute : entry' and I doubt that this is CF compliant. 
As mentioned, this only happens with  the global attributes title, history, institution, source, references, and comment.
So, my file, there is an inconsistency, as sometimes there is a "string :" and sometimes not., see my example below.
I think that this aspect should be somehow covered by the checker. 

```
ncdump -h  lwtns06_1986.nc
// global attributes:
		:source = "National Centers for Environmental Prediction/National Weather Service/NOAA/U.S. Department of Commerce. 1994, updated monthly. NCEP/NCAR Global Reanalysis Products, 1948-continuing. Research Data Archive at NOAA/PSL: /data/gridded/data.ncep.reanalysis.html. \nKalnay et al.,The NCEP/NCAR 40-year reanalysis project, Bull. Amer. Meteor. Soc., 77, 437-470, 1996. \nNCEP Reanalysis data provided by the NOAA/OAR/ESRL PSL, Boulder, Colorado, USA, from their Web site at https://psl.noaa.gov/data/gridded/data.ncep.reanalysis.surface.html" ;
		string :institution =  = "Bundesamt für Seeschifffahrt und Hydrographie, Bernhard-Nocht-Straße 78, 20359 Hamburg, Germany" ;
		:Conventions = "CF-1.8 ATMODAT-3.0" ;
		string :creator = "Peter Loewe, Bundesamt für Seeschifffahrt und Hydrographie (BSH), ORCID: 0000-0001-8243-2111, url: https://www.bsh.de/EN/Home/home_node.html" ;

and so forth
```

Thanks.

**Comment by jkretz** [comment]
The reason for the `string :` you get here is due to the use of special character (e.g. umlaut in "für"). If you want to get rid of it, just replace/remove the special characters in the string. 
At the moment, there is nothing defined in the ATMODAT standard that forbids the use of special characters, so we don't check for their presence. Unless we forbid the use of special characters in attribute strings, there is no option to filter out such cases as we only check for the presence of an attribute and if the string fulfills possible requirements to it.
