### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by wachsylon** [AtMoDat/atmodat_data_checker#109]
Hi,
when I install the atmodat-checklib now with
`pip install git+https://github.com/AtMoDat/atmodat_data_checker`,
and run
`run_checks -f somefile`,
I get
`FileNotFoundError: [Errno 2] No such file or directory: '/home/k/k204210/miniconda3/envs/mambaenvH/envs/taucenv/lib/python3.9/site-packages/atmodat_checklib/AtMoDat_CVs/atmodat_standard_checks.yml'`
where the parent folder `atmodat_checklib` does not contain `AtMoDat_CVs`. The log from pip install say:
`Running command git submodule update --init --recursive -q`
so I think the problem here is that the submodule `AtMoDat_CVs` is not copied with the package. Do you have an idea why?
Best,
Fabi

**Comment by jkretz** [comment]
I recently modified some things to allow for via `pip install git+https://github.com/AtMoDat/atmodat_data_checker`. I thought that I had it running but apparently, there still seems to be an issue in that regard. That also why I haven't updated the readme and the test yet. I will investigate this issue.

**Comment by jkretz** [comment]
It seems that there is an issue that the AtMoDat_CVs is not included in the build process. I will see if there is a fix to that issue

**Comment by jkretz** [comment]
@wachsylon 
I think I found/fixed the issue. It was related to a missing entry in the MANIFEST.in. I was able to install the checker almost solely via pip from this GitHub repo. Maybe you can verify if it works for you:
`conda create --name atmodat_test python=3.8 udunits2`
`conda activate atmodat_test`
`pip install --no-cache-dir git+https://github.com/AtMoDat/atmodat_data_checker@misc_issues` (using --no-cache-dir to build from scratch)

**Comment by wachsylon** [comment]
works. 

but `run_checks` is installed into a path which is not in `$PATH`. that can also be a mistake on my side.
