### ISSUE TITLE
Checker result when prescribed Controlled Vocabulary in recommeded and optional attributes are wrong

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#110]
Hallo, 

I have a simple netcdf file that is as follows:

```
ncdump foo.nc > foo.txt
```
```
cat foo.txt
```
```
netcdf foo {
dimensions:
	time = UNLIMITED ; // (1 currently)
variables:
	double time(time) ;
	float ps(time) ;

// global attributes:
		:source = "myfreetextsource" ;
		:institution = "myfreetextinstitute" ;
		:Conventions = "CF-1.8 ATMODAT-3.0" ;
		:nominal_resolution = "myfreetextnominalresolution" ;
data:

 time = 58631 ;

 ps = 98166 ;
}
```

If you like to test this file, just recreate the netcdf with  

`ncgen -o foo.nc foo.txt
`

The atmodat checker gives the following short_summary.txt
```
more atmodat_checker_output/latest/short_summary.txt
Short summary of checks:

Checking against: atmodat_standard:3.0, CF table version: 78
Version of the AtMoDat checker: 1.1.0
Checked at: 2022-01-21T14:21:23

Number of checked files: 1
Mandatory checks passed: 5/5
Recommended checks passed: 0/19
Optional checks passed: 0/9
CF checker errors: 0
```

In the ATMODAT Standard 3.0 Table 11, nominal_resolution is a recommended attribute and it is stated that the nominal_resolution attribute requires a CV from https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_nominal_resolution.json. 

When I use a dummy string as nominal_resolution attribute entry (in the example "myfreetextnominalresolution"), the short summary output shows no error. 

"Recommended checks passed: 0/19"

I think it is quite a difference if 
- a global attribute is not included in the file header (e.g. because it is not applicable)
- a global attribute is included, but is filled out incorreclty, especially when CVs are prescribed. 

If we prescribe CVs for certain global attributes, then the atmodat checker should make the users aware if they are incorrectly filled. So in my opinion, the short summary output should highlight such errors. 
I propose the following approach:
Recommended checks passed: 0/19 (invalid entries:1, missing entries: 18)

Better (recommended/optional) global metadata are entirely missing than that they contain invalid CV entries. 

Thanks a lot!

Angelika

**Comment by jkretz** [comment]
Would an output like this work for you?

```
Short summary of checks: 
 
Checking against: atmodat_standard:3.0, CF table version: 78 
Version of the AtMoDat checker: 1.2.0
Checked at: 2022-01-24T14:08:49
 
Number of checked files: 1
Mandatory checks passed: 2/4 (0 missing, 2 with error)
Recommended checks passed: 18/20 (1 missing, 1 with error)
Optional checks passed: 9/9 (0 missing, 0 with error)
CF checker errors: 1
CF checker warnings: 7
```

**Comment by atmodatcode** [comment]
Thanks. That looks great!
