### ISSUE TITLE
short summary header

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#112]
Dear jkretz,

the first lines of the short summary txt file currently look like this:

Short summary of checks: 

Checking against: atmodat_standard:3.0, CF table version: 78 
Version of the AtMoDat checker: 1.2.0
Checked at: 2022-01-24T14:08:49

I would recommend changing this into:

=== Short summary === 

ATMODAT Standard Compliance Checker: 1.2.0
Checking against: ATMODAT Standard 3.0, CF version 1.8
Checked at: 2022-01-24T14:08:49

[...]

_Note_: adding the CF version against which the integrated cfchecks tool is checking is more important than adding info on the CF table version that was used in the check....

See also the output generated by cfchecks

```
cfchecks -v 1.9 NO_ATTRIBUTES.nc
WARNING: CF-1.9 is not a valid CF version.
Performing check against newest version: CF-1.8
CHECKING NetCDF FILE: NO_ATTRIBUTES.nc
=====================
Using CF Checker Version 4.1.0
Checking against CF Version CF-1.8
Using Standard Name Table Version 78 (2021-09-21T11:55:06Z)
Using Area Type Table Version 10 (23 June 2020)
Using Standardized Region Name Table Version 4 (18 December 2018)

```

**Comment by atmodatcode** [comment]
almost. Some brackets are missing and I would not write  CF Version CF-1.4, because like this, the CF is redundant. 
If you write "CF version", you can append the numeric CF version. So CF Version 1.4 would be sound. This manner to refer to the conventions is also used in Hassel's GMD paper on the CF-1.6 data model https://doi.org/10.5194/gmd-10-4619-2017. 
E.g. Hassel writes "
Their model differs from ours in four major ways:
1. It is not the complete **CF version 1.6** (for example, it does not appear to include ancillary data variables).




I would think the better way is as follows: 

=== Short summary === 
 
ATMODAT Standard Compliance Checker Version: 1.2.0
Checking against: ATMODAT Standard 3.0, **CF Version 1.4**
Checked at: 2022-01-24T15:23:46
 
Number of checked files: 1
Mandatory checks passed: 2/4 (0 missing, 2 error(s)**)**
Recommended checks passed: 18/20 (1 missing, 1 error(s)**)**
Optional checks passed: 9/9 (0 missing, 0 error(s)**)**
CF checker errors: 1
CF checker warnings: 7

**Comment by jkretz** [comment]
All issues addressed in latest commit of `misc_issues`
