### ISSUE TITLE
get ready for deprecation frame.append method used in summary_creation_util.py

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#113]
When I use AtMoDat checker: 1.2.0, I obtain the FutureWarning that frame.append method is deprecated and will be removed from pandas in a future version. **Use pandas.concat instead.**

This means we would need to adjust the code in term.

**Comment by jkretz** [comment]
I have never seen that message before. Can you specify where exactly you encountered it?

**Comment by atmodatcode** [comment]
I freshly installed the atmodat_test branch on my mac. 

angelika ~: conda activate atmodat_test
(atmodat_test) angelika ~: cd adc/demo_data/
(atmodat_test) angelika ~/adc/demo_data: run_checks -s -f CMIP6_ATTRIBUTES.nc
Running Compliance Checker on the datasets from: ['CMIP6_ATTRIBUTES.nc']
2022-01-25 08:23:04.838918 [INFO] :: PYESSV :: Loading vocabularies from /Users/angelika/anaconda3/envs/atmodat_test/lib/python3.8/site-packages/atmodat_checklib/AtMoDat_CVs/pyessv-archive:
2022-01-25 08:23:04.863251 [INFO] :: PYESSV :: ... loaded: atmodat
/Users/angelika/anaconda3/envs/atmodat_test/lib/python3.8/site-packages/atmodat_checklib/utils/summary_creation_util.py:181: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  json_summary = json_summary.append(extract_overview_output_json(file),
--- 3.0687 seconds for checking 1 files---
(atmodat_test) angelika ~/adc/demo_data: conda -V
conda 4.11.0

**Comment by jkretz** [comment]
@atmodatcode 
Can you varify if this messages is still present with the latest version of `misc_issues`
