### ISSUE TITLE
Required environment variables

### ISSUE THREAD

**Issue by wachsylon** [AtMoDat/atmodat_data_checker#120]
Hi,

I think this `try except` [sentence](https://github.com/AtMoDat/atmodat_data_checker/blob/29cb5e377e12b287c78f7953a906e4353f39fe1a/atmodat_checklib/utils/env_util.py#L9) is too restrict. It leads to errors like seen [here](https://data-infrastructure-services.gitlab-pages.dkrz.de/tutorials-and-use-cases/tutorial_data-quality_atmodat-checker.html#application).

You can have an installation of atmodat-checker without having these conda env variables, I guess.

Best,
Fabi

**Comment by wachsylon** [comment]
I try to show a different method in this [pr](https://github.com/AtMoDat/atmodat_data_checker/pull/121) however it was made on the fly and I already appologize if it is bad quality :)

**Comment by wachsylon** [comment]
@jkretz

**Comment by jkretz** [comment]
@wachsylon Ah sorry, I will have a look at it.
