### ISSUE TITLE
-cfv auto is not working

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#125]
Hello, 
when running the atmodat checker over a directory, I noted that in the latest version of the atmodat checker, the -cfv auto doesn't work. It is always checking against the CF version that is specified in the  Conventions attribute of the first netCDF file that was checked. 
e.,g.

```
for FILE in `ls CFdata/*.nc\`;do echo "$FILE:`ncdump -h $FILE|grep :Conventions`";done
```
CFdata/BSH_simple-Lamb_testfile.nc:		:Conventions = "CF-1.8 ATMODAT-3.0" ;
CFdata/BSH_simple-Lamb_testfile_CF1.7.nc:		:Conventions = "CF-1.7 ATMODAT-3.0" ;
CFdata/CanESM2_rcp85_growing_degree_days_gt_4_annual_ts1-2.nc:		:Conventions = "CF-1.5" ;
CFdata/CanESM2_rcp85_growing_degree_days_gt_4_annual_ts1-2_degree-days.nc:		:Conventions = "CF-1.5" ;

```
run_checks -s -p CFdata -cfv auto -op mycheckresult
```
Running Compliance Checker on the dataset from: CFdata/BSH_simple-Lamb_testfile_CF1.7.nc
2022-05-17 10:07:05.956709 [INFO] :: PYESSV :: Loading vocabularies from /home/k/k204232/atmodat_data_checker/atmodat_checklib/AtMoDat_CVs/pyessv-archive:
2022-05-17 10:07:05.982313 [INFO] :: PYESSV :: ... loaded: atmodat
Running Compliance Checker on the dataset from: CFdata/BSH_simple-Lamb_testfile.nc
Running Compliance Checker on the dataset from: CFdata/CanESM2_rcp85_growing_degree_days_gt_4_annual_ts1-2.nc
Running Compliance Checker on the dataset from: CFdata/CanESM2_rcp85_growing_degree_days_gt_4_annual_ts1-2_degree-days.nc
--- 2.1649 seconds for checking 4 files---
```
for FILE in `ls mycheckresult/atmodat_checker_output/latest/CF/*.txt`;do echo "$FILE:`grep against $FILE`";done
```
mycheckresult/atmodat_checker_output/latest/CF/BSH_simple-Lamb_testfile_CF1.7_CF_result.txt:Checking against CF Version CF-1.7
mycheckresult/atmodat_checker_output/latest/CF/BSH_simple-Lamb_testfile_CF_result.txt:Checking against CF Version CF-1.7
WARN: (2.6.1): Inconsistency - This netCDF file appears to contain CF-1.8 data, but you've requested a validity check against CF-1.7
mycheckresult/atmodat_checker_output/latest/CF/CanESM2_rcp85_growing_degree_days_gt_4_annual_ts1-2_CF_result.txt:Checking against CF Version CF-1.7
WARN: (2.6.1): Inconsistency - This netCDF file appears to contain CF-1.5 data, but you've requested a validity check against CF-1.7
mycheckresult/atmodat_checker_output/latest/CF/CanESM2_rcp85_growing_degree_days_gt_4_annual_ts1-2_degree-days_CF_result.txt:Checking against CF Version CF-1.7
WARN: (2.6.1): Inconsistency - This netCDF file appears to contain CF-1.5 data, but you've requested a validity check against CF-1.7

Related to this, there is a bug when running 
```
run_checks -s -p CFdata/ -check CF -op mycheckresults
```
Traceback (most recent call last):
  File "/home/k/k204232/.conda/envs/atmodat/bin/run_checks", line 33, in <module>
    sys.exit(load_entry_point('atmodat-checklib', 'console_scripts', 'run_checks')())
  File "/home/k/k204232/atmodat_data_checker/run_checks.py", line 103, in main
    summary_creation.create_output_summary(file_counter, opath_run, check_types)
  File "/home/k/k204232/atmodat_data_checker/atmodat_checklib/utils/summary_creation_util.py", line 207, in create_output_summary
    write_short_summary(json_summary, cf_version, cf_errors, cf_warns, incorrect_formula_term_error, file_counter,
  File "/home/k/k204232/atmodat_data_checker/atmodat_checklib/utils/summary_creation_util.py", line 124, in write_short_summary
    if cf_version_string == 'multiple CF versions':
UnboundLocalError: local variable 'cf_version_string' referenced before assignment

Thanks
Angelika

**Comment by jkretz** [comment]
Nice spots.

Your first point is related to an issue with the CF-Checker, as it only runs the automatic recognition of the CF version on the first file. This does not make much sense to me if you allow for multiple files to be checked. Some time ago, I revised how the CF-Checker is being called to check the files. I will revert that change in an upcoming PR for the time being, which should not be too much work. I will nevertheless submit an issue in the CF-Checker repo so that they can fix the automatic recognition of the CF version.

Your second point will require some minor adaptations, which I will also include in the PR mentioned above.
