### ISSUE TITLE
-cfv should allow for CF conventions 1.9

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#127]
I noted that
```
 run_checks -s -p CFdata1.7/ -check CF -cfv 1.9 -op t7
User-defined -cfv option invalid; using 'auto' instead
```

CF Conventions 1.9 has been released in September 2021: https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html

We should allow checking against it. Currently, only checking up to version 1.8 is allowed. Thanks!

**Comment by jkretz** [comment]
True, but this hasn't been implemented into the CF-Checker, so we can't check for this version. I will close this issue for now.
