### ISSUE TITLE
change of repo title

### ISSUE THREAD

**Issue by am-kaiser** [AtMoDat/atmodat_data_checker#23]
change of repository name to atmodat_standard_data_file_checker to make a clear distinction to the dataCite checker. Are you ok with that @jkretz ?

**Comment by am-kaiser** [comment]
or maybe without standard? i.e. atmodat_data_file_checker

**Comment by jkretz** [comment]
I think the first title is too long. The second suggestion is okay, but I would maybe suggest to also remove "file" so the title would be "atmodat_data_checker"

**Comment by am-kaiser** [comment]
ok im fine with atmodat_data_checker
