### ISSUE TITLE
Raise error if global attribute "Conventions" contains incorrect ATMODAT version

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#41]
Currently, there is no check for this. If Conventions is e.g. "CF-1.8 ATMODAT-99", this wouldn't raise any error.

**Comment by jkretz** [comment]
The same holds in principle for the version number of the CF-Conventions. There is a warning by the CF checker that it is not all valid version if the version chosen is greater then 1.7. In this case it will simply revert to the latest version of the CF-Conventions.
For the AtMoDat version, one could simply sets up a new check that also reads the version number to check against, which is defined in the respective *.yml. On could do something similar for CF, even though we would need to keep track of the latest version number of the CF-Conventions

**Comment by jkretz** [comment]
I already started to work on that issue. For the CF Convention version, you can define a valid range in the yaml were the checks are defined. The same goes for the AtMoDat Standard version, which is set to be in accordance with the respective yaml were the version of the AtMoDat Standard is defined against which checks are performed. I will set up a PR as soon as #42 land
