### ISSUE TITLE
atmodat data checker misses for checking mandatory global attribute "source"

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#57]
The global attribute "source" is a mandatory ATMODAT standard global attribute. 
The current version of the checker does not check file(s) for this attribute. 
This has to be urgently added.

**Comment by jkretz** [comment]
Fixed with https://github.com/AtMoDat/atmodat_data_checker/commit/6c0184be794f2b0d7edfc0d75eb65cb1c64bf633.
