### ISSUE TITLE
Remove [INFO] :: PYESSV output to standard output when running run_checks.py  

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#58]
2021-09-05 13:56:30.124302 [INFO] :: PYESSV :: Loading vocabularies from /Users/angelika/Checker/atmodat_data_checker/AtMoDat_CVs/pyessv-archive:
2021-09-05 13:56:30.161607 [INFO] :: PYESSV :: ... loaded: atmodat

**Comment by jkretz** [comment]
As already discussed via mail, it is not possible to get rid of this message as this message does not stem from our codebase. It is part of pyessv and is automatically outputted whenever the pyessv module is loaded as part of our CV checks. As long as we want to use pyessv to check our CV, there is nothing we can do about it. I will therefore close this issue for now.

**Comment by jkretz** [comment]
I think I found a way of how to disable these messages. I will include it in a future PR
