### ISSUE TITLE
check for featureType falsely raises error

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#59]
featureType is an optional ATMODAT attribute. 
According to Table 11, featureType contains CV from CF-1.8. 
These CVs include, e.g. point, timeSeries. 
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#discrete-sampling-geometries

Whatever CV from that list is used for featureType, the run_checks.py raises an error. 

This should be fixed with priority

**Comment by jkretz** [comment]
This is related to https://github.com/AtMoDat/AtMoDat_CVs/issues/4 . I will work on it
