### ISSUE TITLE
create a summary statistics of license attribute

### ISSUE THREAD

**Issue by atmodatcode** [AtMoDat/atmodat_data_checker#71]
For juristic reasons, data curators would need to know whether files in a folder contain the same global attribute value for license  
It would be great if the atmodat checker summarises the used licences: 
e.g.
summary_used_licences.txt:
"CC-BY 4.0”
"CC-BY 4.0 ”    '-- with additional blank

or 
summary_used_licences.txt
"CC-BY 4.0”
"CC BY-SA 2.0”

In the first example, the same licence is used; there is just a non-relevant spelling difference (additional black at the end of the entry).

In the second example, the curators see that the files in the folders do not all have the same licence. In this case, curators would need to discuss with data producers how do publish the data as they cannot be published together with a single DOI for a dataset group. 

I propose an optional additional flag "-lic"  to the run_checks routine
run_checks.py -s -op xy -lic

Thanks
Angelika

**Comment by jkretz** [comment]
As the license attribute can be in free form, it is difficult to extract the license information. The `ALL_ATMODAT_ATTRIBUTES.nc` in the demo data is exemplary for such a situation. 
@atmodatcode  we need to discuss how to approach such a case.

**Comment by jkretz** [comment]
This has been added to the checker. It is an default output, so now command line attributes needed
